### ISSUE TITLE
Generate Labels for Expression elements

### ISSUE THREAD

**Issue by bjorncole** [bjorncole/pyMBE#33]
To support Notebook playback, synching to other tools, etc., the abstract syntax of an Expression tree needs to be serialized into a label. For example, we have something like

Expression
    operation '+'
        parameter a
        parameter b
        return parameter c

Should render as 'a + b = c'

**Comment by bjorncole** [comment]
Is there a Python library for turning expression Abstract Syntax Trees into readable equations?

**Comment by sanbales** [comment]
Is there a way to get the specification for how expressions are defined in SysML2?  E.g., do they always have two parameters, what are the list of operators allowed, is it different for any subclasses of `Expression`?

I think AST may be overkill for this, but if we go that route, we will need something something that "comprehends" how expressions work in SysML2/KERML.  That ECore model would help but may need to get the PDF of the spec to get more context.

**Comment by bjorncole** [comment]
The operators and expressions are defined in libraries like IntegerFunctions:
https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/master/sysml.library/Kernel%20Libraries/Kernel%20Function%20Library/IntegerFunctions.kerml

You should have MMS access to the spec as part of your one-time membership in SST (or at least Mike or Richard should ... someone in the group who represents GTRI):
https://mms.openmbee.org/alfresco/mmsapp/mms.html#/projects/PROJECT-6b2e436d-1f8c-4b06-8cd9-a8f89df02bb5/master/documents/_18_5_3_64a0213_1551820456660_61987_17755/views/_19_0_2_59601fc_1592067981859_836419_959
